config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'questions#dashboard'
  get '/ressources', to: 'pages#ressources'
  get '/qcm', to: 'questions#qcm'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :questions do
    resources :answers, only: [:edit, :update]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :good_prop, presence: true

  enum good_prop: { un: 1, deux: 2, trois: 3}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_one :answer, dependent: :destroy

  accepts_nested_attributes_for :answer, allow_destroy: true

  validates :level, presence: true
  validates :category, presence: true
  validates :statement, presence: true, length: { minimum: 2}
  validates :prop_one, presence: true, length: { minimum: 2}
  validates :prop_two, presence: true, length: { minimum: 2}
  validates :prop_three, presence: true, length: { minimum: 2}

  enum level: { départemental: 1, régional: 2}
  enum category: { généralités: 1, fleuret: 2, épée: 3, sabre: 4}

  scope :dep_g, -> { where(level: 1).where(category: 1)}
  scope :dep_f, -> { where(level: 1).where(category: 2)}
  scope :dep_e, -> { where(level: 1).where(category: 3)}
  scope :dep_s, -> { where(level: 1).where(category: 4)}
  scope :reg_g, -> { where(level: 2).where(category: 1)}
  scope :reg_f, -> { where(level: 2).where(category: 2)}
  scope :reg_e, -> { where(level: 2).where(category: 3)}
  scope :reg_s, -> { where(level: 2).where(category: 4)}

  def self.filter_by_level(level)
    where(level: level)
  end

  def self.filter_by_category(category)
    where(category: category)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions

  validates :first_name, presence: true, length: { minimum: 2}
  validates :last_name, presence: true, length: { minimum: 1}
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :encrypted_password, presence: true

  enum role: { normal: 0, contributor: 1, admin: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :qcm], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :qcm], unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  #Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :ressources ]

  def home
  end

  def ressources
  end
end

app/controllers/questions_controller.rb
require 'will_paginate/array' #needed to work with arrays

class QuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :qcm]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = policy_scope(Question).order(created_at: :desc)
    @questions = @questions.filter_by_level(params[:level]) if params[:level].present?
    @questions = @questions.filter_by_category(params[:category]) if params[:category].present?
    @count = @questions.length
    @questions = @questions.paginate(page: params[:page], per_page: 1)
  end

  def qcm
    @level = params[:level]
    @category = params[:category]
    @questions = policy_scope(Question)
    @questions_generales = @questions.filter_by_level(params[:level]).where(category: 1).shuffle if @level.present?
    @questions_specifiques = @questions.filter_by_level(params[:level]).filter_by_category(params[:category]).shuffle if @level.present? && @category.present?
    if @level == 'départemental'
      @questions_generales = @questions_generales.first(12)
      @questions_specifiques = @questions_specifiques.first(8)
    else
      @questions_generales = @questions_generales.first(20)
      @questions_specifiques = @questions_specifiques.first(10)
    end
  end

  def show
  end

  def new
    @user = current_user
    @question = Question.new
    @question.user = @user
    authorize @question
  end

  def create
    @user = current_user
    @question = Question.new(question_params)
    @question.user = @user
    authorize @question
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @answer = @question.answer
  end

  def update
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  def dashboard
    current_user.contributor? ? @questions = Question.where(user_id: current_user) : @questions = Question.all
    @questions_dep_g = @questions.dep_g
    @questions_dep_f = @questions.dep_f
    @questions_dep_e = @questions.dep_e
    @questions_dep_s = @questions.dep_s
    @questions_reg_g = @questions.reg_g
    @questions_reg_f = @questions.reg_f
    @questions_reg_e = @questions.reg_e
    @questions_reg_s = @questions.reg_s
    authorize @questions
  end

  private

  def set_question
    @question = Question.find(params[:id])
    authorize @question
  end

  def question_params
    params.require(:question).permit(:statement, :prop_one, :prop_two, :prop_three, :level, :category, answer_attributes: [:id, :explanation, :good_prop])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/meta_tags_helpers.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <%= favicon_link_tag "favicon.ico" %>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <% if user_signed_in? %>
    <body id="body" data-logged="true">
  <% else %>
    <body id="body" data-logged="false">
  <% end %>
    <%= render 'shared/navbar' %>
    <div class="main-container">
      <%= render 'shared/banner' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container" role="main">
  <div class="home-text">
    <div class="home-text-welcome">
      <p>
      L'objectif de ce site est de vous permettre de vous entraîner au qcm d'arbitrage,
      première étape pour entrer en formation d'arbitre départemental ou régional.<br>
      Nous vous conseillons vivement de lire au préalable les différents documents disponibles
      dans la rubrique <%= link_to "Ressources", ressources_path %>.<br>
      Vous avez la possibilité soit de sélectionner un type de questions, soit de passer un
      qcm complet chronométré (20 min pour le départemental, 30 minutes pour le régional).<br>
      <span>Bon entraînement !</span>
      </p>
      <div class="home-text-btns">
        <button class="btn-blue select-questions"> Sélectionner des questions</button>
        <button class="btn-blue complete-qcm"> QCM complet chronométré</button>
      </div>
    </div>
    <!-- au clic sur selectionner des questions -->
    <div class="filters-questions hide-element">
      <h2>Choix du type de questions</h2>
      <%= form_with(url: questions_path, method: 'get', local: true, class: "question-search-form") do %>
        <div class="question-search">
          <div class="question-category-search">
            <h3>Catégorie :</h3>
            <div class="question-category-inputs">
              <div class="categories-choice">
                <%= label_tag "questions-category-general", 'Généralités' %>
                <%= radio_button_tag 'category', 'généralités', false, required: true %>
              </div>
              <div class="categories-choice">
                <%= label_tag "questions-category-fleuret", 'Spécifique fleuret' %>
                <%= radio_button_tag 'category', 'fleuret', false, required: true %>
              </div>
              <div class="categories-choice">
                <%= label_tag "questions-category-epee", 'Spécifique épée' %>
                <%= radio_button_tag 'category', 'épée', false, required: true %>
              </div>
              <div class="categories-choice">
                <%= label_tag "questions-category-sabre", 'Spécifique sabre' %>
                <%= radio_button_tag 'category', 'sabre', false, required: true %>
              </div>
            </div>
          </div>
          <div class="question-level-search">
            <h3>Niveau :</h3>
            <div class="question-level-inputs">
              <div class="levels-choice">
                <%= label_tag "questions-level-dep", 'Départemental' %>
                <%= radio_button_tag 'level', 'départemental', false, required: true %>
              </div>
              <div class="levels-choice">
                <%= label_tag "questions-level-reg", 'Régional' %>
                <%= radio_button_tag 'level', 'régional', false, required: true %>
              </div>
            </div>
          </div>
        </div>
        <div class="filters-buttons">
          <%= submit_tag 'Commencer', class: 'btn-blue submit-questions-choice ' %>
          <a href="/" class='btn-blue'><i class="fas fa-backward"></i> Accueil</a>
        </div>
      <% end %>
    </div>
    <!-- au clic sur qcm complet -->
    <div class="filters-questions-qcm hide-element">
      <h2>Choix du type de QCM</h2>
      <%= form_with(url: qcm_path, method: 'get', local: true, class: "question-search-form") do %>
        <div class="question-search">
          <div class="question-category-search">
            <h3>Catégorie :</h3>
            <div class="question-category-inputs">
              <div class="categories-choice-qcm">
                <%= label_tag "questions-category-fleuret", 'Fleuret' %>
                <%= radio_button_tag 'category', 'fleuret', false, required: true %>
              </div>
              <div class="categories-choice-qcm">
                <%= label_tag "questions-category-epee", 'Épée' %>
                <%= radio_button_tag 'category', 'épée', false, required: true %>
              </div>
              <div class="categories-choice-qcm">
                <%= label_tag "questions-category-sabre", 'Sabre' %>
                <%= radio_button_tag 'category', 'sabre', false, required: true %>
              </div>
            </div>
          </div>
          <div class="question-level-search">
            <h3>Niveau :</h3>
            <div class="question-level-inputs">
              <div class="levels-choice">
                <%= label_tag "questions-level-dep", 'Départemental' %>
                <%= radio_button_tag 'level', 'départemental', false, required: true  %>
              </div>
              <div class="levels-choice">
                <%= label_tag "questions-level-reg", 'Régional' %>
                <%= radio_button_tag 'level', 'régional', false, required: true %>
              </div>
            </div>
          </div>
        </div>
        <div class="filters-buttons">
          <%= submit_tag 'Commencer le qcm', class: 'btn-blue submit-qcm-choice' %>
          <a href="/" class='btn-blue'><i class="fas fa-backward"></i> Accueil</a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/references.html.erb
<div class="references-container" role="main">
  <div class="references-text">
      <h2>Documentation à consulter</h2>
      <h3>International</h3>
        <ul class="fa-ul">
        <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://static.fie.org/uploads/26/131727-Technique%20fra.pdf" target="_blank">Règlement technique (décembre 2021)</a></li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://static.fie.org/uploads/24/124001-t.170%20fra_juil20.pdf" target="_blank">Article t170, tableau des fautes et sanctions (juillet 2020)</a></li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://static.fie.org/uploads/26/131730-Organisation%20fra.pdf" target="_blank">Règles d'organisation (décembre 2021)</a></li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://static.fie.org/uploads/26/131721-RMATER%20fra.pdf" target="_blank">Règlement du matériel (décembre 2021)</a></li>
        </ul>
      <h3>National</h3>
        <ul class="fa-ul">
          <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://www.escrime-ffe.fr/medias/fichiers/Vie%20Sportive/CALENDRIER%20SPORTIF/FFE_RS21_22.pdf" target="_blank">Règlement sportif (octobre 2021)</a></li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://www.escrime-ffe.fr/medias/fichiers/Arbitrage/règlement%20et%20doc%20/Formation%20arbitre%20epee658586142.pdf" target="_blank">Formation arbitre épée</a></li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://www.escrime-ffe.fr/medias/fichiers/Arbitrage/règlement%20et%20doc%20/Formation%20arbitre%20fleuret%20sabre1496506219.pdf" target="_blank">Formation arbitre fleuret/sabre</a></li>
        </ul>
      <h3>Régional</h3>
      <ul class="fa-ul">
        <li class="references-last-li"><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://escrime-iledefrance.fr/pratiquer-et-sengager/devenir-arbitre-escrime" target="_blank">Devenir arbitre d'escrime</a></li>
      </ul>
  </div>
</div>

app/views/pages/ressources.html.erb
<% content_for :meta_title, "Arbire d'escrime - Ressources" %>
<% content_for :meta_description, "Tous les documents nécessaires pour réviser la règlementation sur l'escrime" %>

<div class="ressources-container" role="main">
  <div class="ressources-text">
      <h2>Documentation à consulter</h2>
      <h3>International</h3>
      <p>Les règlements internationaux sont consultables sur le site de la FIE (lien
        <a href="https://fie.org/fie/documents/rules" target="_blank" class="special-link">ici</a>).
        Nous vous conseillons d'y consulter les éléments suivants :
      </p>
        <ul class="fa-ul">
          <li><span class="fa-li"><i class="fas fa-check"></i></span>Règlement technique</li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span>Article t170, tableau des fautes et sanctions</li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span>Règles d'organisation</li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span>Règlement du matériel</li>
        </ul>
      <h3>National</h3>
        <ul class="fa-ul">
          <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://www.ffescrime.fr/je-suis-en-club/competiteurs/reglements/" target="_blank">Règlements sportifs (saison 2023/2024)</a></li>
          <li><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://www.ffescrime.fr/je-suis-en-club/arbitres/reglements-arbitrage/" target="_blank">Règlements d'arbitrage (saison 2023/2024)</a></li>
        </ul>
      <h3>IDF</h3>
      <ul class="fa-ul">
        <li class="ressources-last-li"><span class="fa-li"><i class="fas fa-check"></i></span><a href="https://escrime-iledefrance.fr/pratiquer-et-sengager/devenir-arbitre-escrime" target="_blank">Devenir arbitre d'escrime</a></li>
      </ul>
  </div>
</div>

app/views/questions/dashboard.html.erb
<div class="questions-dashboard-container">
  <div class="dashboard-dep">
    <h3>Niveau Départemental</h3>
      <h4>Généralités</h4>
        <% @questions_dep_g.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4>Fleuret</h4>
        <% @questions_dep_f.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4>Épée</h4>
        <% @questions_dep_e.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4>Sabre</h4>
        <% @questions_dep_s.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %></li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
  </div>
  <div class="dashboard-reg">
    <h3>Niveau Régional</h3>
      <h4>Généralités</h4>
        <% @questions_reg_g.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4>Fleuret</h4>
        <% @questions_reg_f.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4>Épée</h4>
        <% @questions_reg_e.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
      <h4>Sabre</h4>
        <% @questions_reg_s.each do |question| %>
          <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-check"></i></span><%= question.statement.first(80) %>...</li><%= link_to '<i class="fas fa-expand"></i>'.html_safe, question_path(question), title: "Voir" %>
          </ul>
        <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="edit-question-container">
  <h3>Modifier une question</h3>
  <%= simple_form_for(@question) do |f| %>
  <div class="edit-question-level">
    <%= f.input :level, as: :radio_buttons, label: "Niveau", collection: [["départemental", "départemental"], ["régional", "régional"]] %>
  </div>
  <div class="edit-question-category">
    <%= f.input :category, as: :radio_buttons, label: "Catégorie", collection: [["généralités", "généralités"], ["fleuret", "fleuret"], ["épée", "épée"], ["sabre", "sabre"]] %>
  </div>
  <%= f.input :statement, :label => "Énoncé de la question" %>
  <%= f.input :prop_one, :label => "Réponse une" %>
  <%= f.input :prop_two, :label => "Réponse deux" %>
  <%= f.input :prop_three, :label => "Réponse trois" %>
  <div class="edit-question-answer">
    <%= f.simple_fields_for :answer do |a| %>
      <%= a.input :good_prop, as: :radio_buttons, label: "Bonne réponse", collection: [["Réponse une", "un"], ["Réponse deux", "deux"], ["Réponse trois", "trois"]], _destroy: '1' %>
      <%= a.input :explanation, label: "Explication de la réponse", _destroy: '1' %>
    <% end %>
  </div>
  <div class="edit-questions-links">
    <%= f.submit "Valider les modifications", class: "btn-blue submit-edit-question" %>
    <%= link_to "Annuler les modifications", :back, class: "btn-blue submit-edit-question" %>
  </div>
  <% end %>
</div>

app/views/questions/index.html.erb
<% content_for :meta_title, "Arbire d'escrime - Questions" %>
<% content_for :meta_description, "Entraînes-toi avec le type de questions sélectionné" %>

<div class="questions-index-container">
<% @questions.each do |question| %>
  <h3><%= @count %> questions de niveau <%= question.level %>, catégorie <%= question.category %></h3>
  <form class="question-index-forms">
    <legend><%= question.statement %> :</legend>
    <label>
      <input name="question" type="radio" value="<%= question.prop_one %>" data-value="un">
      <%= question.prop_one %>
    </label>
    <label>
      <input name="question" type="radio" value="<%= question.prop_two %>" data-value="deux">
      <%= question.prop_two %>
    </label>
    <label>
      <input name="question" type="radio" value="<%= question.prop_three %>" data-value="trois">
      <%= question.prop_three %>
    </label>
    <button class="question-index-form-submit btn-blue" >Valider</button>
  </form>
  <div class="question-index-answer hide-element">
    <p class="right-answer hide-element">La bonne réponse est la réponse <%= question.answer.good_prop %>.</p>
    <p class="answer-explanation" data-value="<%= question.answer.good_prop %>"><%= question.answer.explanation %>.</p>
  </div>
<% end %>
<%= will_paginate @questions, class: "apple_pagination" %>
</div>

app/views/questions/show.html.erb
<div class="show-question-container">
  <h3>Question de niveau <%= @question.level %>, catégorie <%= @question.category %></h3>
  <h4><%= @question.statement %> :</h4>
    <ul class="question-content">
      <li><%= @question.prop_one %></li>
      <li><%= @question.prop_two %></li>
      <li><%= @question.prop_three %></li>
    </ul>
  <h4 class="question-answer-content">La bonne réponse est la réponse <%= @question.answer.good_prop %>.</h4>
  <p><%= @question.answer.explanation %>.</p>
  <div class="show_question-bottom-links">
    <%= link_to "Modifier",  edit_question_path(@question), class: "btn-blue" %>
    <%= link_to "Supprimer", question_path(@question), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-blue" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-left-links">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "nav_image.jpg" %>
      <% end %>
      <%= link_to "Accueil", root_path, class: "nav-link" %>
      <%= link_to "Ressources", ressources_path, class: "nav-link" %>
      <%= mail_to "contact@escrime-qcm-arbitrage.com", "Contact", class: "nav-link" %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul id="login-signup" class="navbar-nav me-auto">
        <% if user_signed_in? && (current_user.admin? || current_user.contributor?) %>
            <!-- <li class="nav-item dropdown"> -->
              <%#= image_tag "halte.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <!-- <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> -->
                <%= link_to "Ajouter une question", new_question_path, class: "nav-link" %>
                <%= link_to "Voir mes questions", dashboard_path, class: "nav-link" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
             <!--  </div> -->
            <!-- </li> -->
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% if  controller.action_name == "qcm" %>
      <%= render 'shared/timer' %>
<% end %>